version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Building application..."
      - echo "Zipping functions..."
      # add new functions to zip below
      - zip -r lambda_1.zip lambda-project-1

artifacts:
  files:
    - lambda_1.zip