version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11

  build:
    commands:
      - echo "Running unit tests..."
      - python -m unittest discover tests/

artifacts:
  files:
    - lamdaFunction1.py
